<?php
/**
 * Simple admin guide page for DOCX placeholders and examples
 */
?>

<?= $this->extend('layouts/default') ?>

<?= $this->section('content') ?>

<div class="container mt-4">
    <h1><?= esc($title) ?></h1>

    <p>This page documents the template variables you can use in DOCX templates generated by the system.</p>

    <h2>Global placeholders</h2>
    <ul>
        <li><code>${FORM_ID}</code> - Form database ID</li>
        <li><code>${FORM_CODE}</code> - Form code</li>
        <li><code>${FORM_DESCRIPTION}</code> - Form description</li>
        <li><code>${SUBMISSION_ID}</code> - Submission ID</li>
        <li><code>${SUBMISSION_DATE}</code> - Submission date</li>
        <li><code>${GENERATED_DATE}</code> - Document generation date</li>
        <li><code>${GENERATED_BY}</code> - Current user full name</li>
    </ul>

    <h2>Field placeholders</h2>
    <p>For each form field you can use the following placeholder patterns. Replace <code>fieldname</code> with the actual field name.</p>

    <ul>
        <li><code>${fieldname}</code> - Full value stored for the field (useful for plain text fields)</li>
        <li><code>${F_fieldname}</code> - First selected value (if multi-select), or the value for single-select fields</li>
        <li><code>${B_fieldname}</code> - Compact block listing each option on its own line; selected options are prefixed with ◉</li>
        <li><code>${A_fieldname_1}</code>, <code>${A_fieldname_2}</code>, ... - Per-option placeholders: contain the option text only when that option is selected, otherwise empty</li>
    </ul>

    <h2>Short aliases by checkbox field order</h2>
    <p>For convenience the system also exposes short, field-less aliases for checkbox-like fields in the order they appear in the panel:</p>
    <ul>
        <li>First checkbox field: <code>${A_1}</code>, <code>${A_2}</code>, ...</li>
        <li>Second checkbox field: <code>${B_1}</code>, <code>${B_2}</code>, ...</li>
        <li>Third checkbox field: <code>${C_1}</code>, <code>${C_2}</code>, ...</li>
    </ul>

    <h2>Examples</h2>
    <h3>Single-select (radio/dropdown) named <code>colour</code></h3>
    <p>Template usage:</p>
    <pre><code>${colour}
${F_colour}
${B_colour}
${A_colour_1}
${A_colour_2}
${A_colour_3}</code></pre>

    <h3>Multi-select (checkboxes) named <code>features</code></h3>
    <p>Template usage:</p>
    <pre><code>${features}
${F_features}
${B_features}
${A_features_1} ${A_features_2} ${A_features_3}

Short aliases (first checkbox field):
${A_1} ${A_2} ${A_3}</code></pre>

    <h2>Notes</h2>
    <ul>
        <li>Matching of option strings is case-insensitive.</li>
        <li>Short aliases are panel-order based and may collide if you include multiple panels or nested templates. Use the namespaced <code>A_fieldname_n</code> placeholders when possible.</li>
        <li>If you want <code>${F_fieldname}</code> to contain all selected values (comma-separated) instead of only the first, ask and I will change it.</li>
    </ul>

</div>

<?= $this->endSection() ?>
